# Generated by Django 5.1.3 on 2024-11-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_alter_inmueble_latitud_alter_inmueble_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoprovincia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inmuebles.pais', to_field='codigo'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
