# Generated by Django 5.1.3 on 2024-11-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_alter_estadoprovincia_pais_alter_pais_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadoprovincia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadoprovincia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_inmuebles.pais'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
