# Generated by Django 5.1.3 on 2024-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0004_alter_ciudad_id_alter_estadoprovincia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
