# Generated by Django 5.1.3 on 2024-11-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0006_alter_pais_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Nulo'), (1, 'arrendador'), (2, 'arrendatario'), (3, 'administrador')], default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
